=== pukou/BS-NIS-Test/BS-NIS-Core/target/classes/com/bsoft/nis/core/schema/config/nisconfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

-->
<xsd:schema xmlns="http://www.bsoft.com.cn/nis/schema/config"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.bsoft.com.cn/nis/schema/config"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified" version="5.6.1">
    <!--总体xml架构模板-->
    <xsd:element name="configs">
        <xsd:complexType>
            <xsd:all>
                <xsd:element maxOccurs="1" minOccurs="0" ref="system"/>
                <xsd:element maxOccurs="1" minOccurs="0" ref="flowGroups"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--系统配置模板-->
    <xsd:element name="system">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="1" minOccurs="1" name="organization">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required" type="organizationScope"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element minOccurs="1" maxOccurs="1" name="mqttclienturl">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element minOccurs="1" maxOccurs="1" name="advicePlanMerge">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element minOccurs="1" maxOccurs="1" name="dataTransferOutHospitalDays">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element minOccurs="1" maxOccurs="1" name="dataTransferDays">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element minOccurs="1" maxOccurs="1" name="CommonDB">
                    <xsd:complexType>
                        <xsd:attribute name="value" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!--流程控制模板-->
    <xsd:element name="flowGroups">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="flowGroup"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="flowGroup">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="flow"/>
            </xsd:sequence>
            <xsd:attribute name="id" use="required" type="flowControllScope"/>
            <xsd:attribute name="remark" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="flow">
        <xsd:complexType>
            <xsd:attribute name="flowName" use="required" type="xsd:string"/>
            <xsd:attribute name="flowHandlerClass" use="required" type="flowScope"/>
            <xsd:attribute name="flowRemark" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>

    <!--枚举-->
    <xsd:simpleType name="organizationScope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="0"/>
            <xsd:enumeration value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="flowControllScope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="adviceExcuteFlow"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="flowScope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.AdviceGeneralCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.CommonControl"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.DoubleCheckControl"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.OralGeneralCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.TransfusionDosingCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.SkinTestCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.InjectionDosingCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.PlanGeneralCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.InjectionGeneralCheck"/>
            <xsd:enumeration value="com.bsoft.nis.adviceexecute.FlowControl.TransfusionGeneralCheck"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== pukou/BS-NIS-Test/BS-NIS/src/main/resources/webconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configs xmlns="http://www.bsoft.com.cn/nis/schema/config"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.bsoft.com.cn/nis/schema/config
                             http://www.bsoft.com.cn/nis/schema/config/nisconfig.xsd">
    <!--系统参数配置
        1.系统参数配置都以key-value的格式书写 key：元素名；value：元素属性value的值
        2.使用方式：调用BS-NIS-CORE包中的ConfigHandler.getSystemConfig(String key)
    -->
    <system>
        <!--多机构判断，1 多机构 0 单机构-->
        <organization value="1"/>
        <!--mqtt服务地址-->
        <mqttclienturl value="tcp://127.0.0.1:1883"/>
        <!--医嘱计划是否与HIS计划合并-->
        <advicePlanMerge value="1"/>
        <!--出院多少天的病人开始数据转移(单位：天)-->
        <dataTransferOutHospitalDays value="30"/>
        <!--只转移多少天的数据-->
        <dataTransferDays value="3"/>

        <CommonDB value="SQLPortal:portal|SQLHIS:hrp|SQLMOBHIS:hrp|SQLCIS:hrp|SQLMOB:mob|SQLENR:enr|SQLMOBENR:enr|SQLEMR:emr|SQLLIS:lis"/>
    </system>

    <!--执行流程组控制
        1.执行流程包含，医嘱执行流程控制，等...
        2.使用方法：
    -->
    <flowGroups>
        <flowGroup  remark="医嘱执行流程控制" id="adviceExcuteFlow">
            <flow flowName="adviceFlow_1" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.CommonControl" flowRemark="基础校验"/>
            <flow flowName="adviceFlow_2" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.AdviceGeneralCheck" flowRemark="医嘱校验"/>
            <flow flowName="adviceFlow_3" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.DoubleCheckControl" flowRemark="双核对校验"/>
            <!--<flow flowName="adviceFlow_4" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.SkinTestCheck" flowRemark="皮试校验"/>-->
            <flow flowName="adviceFlow_5" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.InjectionDosingCheck" flowRemark="注射类加药核对校验"/>
            <flow flowName="adviceFlow_6" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.TransfusionDosingCheck" flowRemark="输液类加药核对校验"/>
            <flow flowName="adviceFlow_7" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.PlanGeneralCheck" flowRemark="医嘱计划校验"/>
            <flow flowName="adviceFlow_8" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.InjectionGeneralCheck" flowRemark="医嘱跟注射明细数据是否匹配校验"/>
            <flow flowName="adviceFlow_9" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.TransfusionGeneralCheck" flowRemark="医嘱跟输液明细数据是否匹配校验"/>
            <flow flowName="adviceFlow_10" flowHandlerClass="com.bsoft.nis.adviceexecute.FlowControl.OralGeneralCheck" flowRemark="医嘱跟口服明细数据是否匹配校验"/>
        </flowGroup>
    </flowGroups>

</configs>
